[config]
default-prelude = "home-runner"

[ubuntu]
required-packages = ["htop", "nload"]

[preludes]
home-runner = "Sets up $PATH to point to ~/.local/bin"

[targets]
# You can define targets without any metadata or options
install-tokio = []

# The most concise way to specify options is as a list of lists
benchmark-tokio = [["num-operations", 10000]]

[targets.setup-rust]
# But you can also define targets in a more verbose
# and human-readable way
options = [
    { name="channel", default="stable", choices=['stable', 'nightly'] }, 
    { name="profile", default="minimal" }
]
about = "Install the rust toolchain"


