[config]
inherits = "basic"

[targets]
install-smol = []

# If you do not set a default value for an option, it is required
benchmark-smol = [["num-operations"]]

[targets.setup-rust]
options = [["channel", "nightly"]]
