name: CI 

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install
        pip install mypy flake8 pytest
    - name: Setup mypy
      run: |
        pip install mypy
        mypy ./wke || true
        mypy --install-types --non-interactive
    - name: Unit Tests
      run: make test
    - name: Lint Checks 
      run: make lint
